### ISSUE TITLE
Any way to see diff data between publishes?

### ISSUE THREAD

**Issue by themeteorchef** [siteleaf/siteleaf-v1-api#10]
Would it be possible to add something to the publish endpoint where we could get back a diff of what's changed since the last publication? 

I'm thinking of a scenario where it would be nice to pull down this info and see a list of what will be changed as a safeguard against making multiple (potentially unwanted) updates.

Maybe something like:

```
{
  changes: [
    { pageId: "blah", postId: "blah" },
    { postId: "blah" },
    { metaId: "blah", metaKey: "blah" }
  ]
}
```

Just ID's here but the more info the better (titles, etc). Thoughts?

**Comment by sskylar** [comment]
For diffs, we'd recommend publishing to GitHub http://www.siteleaf.com/blog/github-pages/
