### ISSUE TITLE
Add JSON examples for POST/PUT-ing meta and taxonomy

### ISSUE THREAD

**Issue by jvhellemond** [siteleaf/siteleaf-v1-api#8]
When POST-ing or PUT-ing a site, page or post, the  documentation mentions:

> meta (optional) — Array of Page metadata

And

> taxonomy (optional) — Array of Taxonomy

I have tried several "structures" for these JSON "arrays", but nothing seems to works. An example would really help here. How can I POST or PUT metadata and taxonomy for sites, pages and posts?

(By the way, there are a few meta/taxonomy typos or mixups in the `README.md` as well)

**Comment by themeteorchef** [comment]
+1 for this. Trying to get this working now and just getting ambiguous errors like this:

```
{ [Error: failed [400] {"error":{"code":"uncaught_error","message":"undefined method `__metadata' for \"[object Object]\":String"}}] stack: [Getter] }
```
For reference, attempted to pass the following to the API:

```
{
  meta: [  "description": "Example of a description meta field." ]
}
```
as well as...

```
{
  meta: [  "key": "description", "value": "Example of a description meta field." ]
}
```
Both throw the error above. Could you clarify the best way to pass meta values? Thanks!

**Comment by sskylar** [comment]
The API will accept `application/x-www-form-urlencoded` (default):

```bash
curl /v1/pages -d "meta[][key]=foo&meta[][value]=bar"
```
or

```bash
curl /v1/pages/:id/meta -d "key=foo&value=bar"
```

The API will also accept `application/json`:

```bash
curl /v1/pages -d '{"meta":[{"key":"foo","value":"bar"}]}' -H 'Content-Type:application/json'
```

or

```bash
curl /v1/pages/:id/meta -d '{"key":"foo","value":"bar"}' -H 'Content-Type:application/json'
```
